### ISSUE TITLE
2.3.0 and Soomla conflicting.

### ISSUE THREAD

**Issue by shakazed** [googleads/googleads-mobile-plugins#111]
Hi!

Just FYI.
The current latest release (2.3.0) and Soomla are conflicting. I'm guessing it's because 2.3.0 now includes support for IAP ads.
When building in Unity you get an "already added" exception on IInAppBillingService$Stub$Proxy.

**Comment by Qbit86** [comment]
Have the same problem after updating `Assets\Plugins\Android\GoogleMobileAdsPlugin\libs\unity-plugin-library.jar` to version 2.3.0.

    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.IllegalArgumentException: already added: Lcom/android/vending/billing/IInAppBillingService$Stub$Proxy;

Old version of jar builds fine into dex. I'm not sure which Unity plugin is in conflict, probably Prime31 plugin for in-app billing.

Please let me know if issue is resolved!

**Comment by ericleich** [comment]
Indeed, the issue is related to changes in 2.3.0 which added support for IAP ads. In 2.3.0, the unity-plugin-library.jar now includes a copy of [com.android.vending.billing.IInAppBillingService.aidl](https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/source/plugin-library/app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl). If you're using other billing plugins, they may do the same thing, and as such Android complains that there is two copies of the file.

We'll leave this issue open while we think more about what the appropriate long-term fix is. In the short term, you can get around this by:

1. Grabbing and opening the [plugin-library](https://github.com/googleads/googleads-mobile-plugins/tree/master/unity/source/plugin-library) source code
2. Removing the aidl file in the project
3. Running `./gradlew makeJar` in Android Studio to rebuild the jar (there is a gradle rule called `makeJar` for this in app/build.gradle)
4. Taking the resulting app/build/libs/unity-plugin-library.jar and putting that into your Unity project

Let me know if you have trouble doing this.

**Comment by ericleich** [comment]
Commit https://github.com/googleads/googleads-mobile-plugins/commit/510548537b81ab3a062d0ad0f2a2d73263fc2798 removes the conflicting aidl file from unity-plugin-library.jar and puts it into a new in-app-billing-service-aidl.jar. There is a version 2.3.1 unity package as well available under [Releases](https://github.com/googleads/googleads-mobile-plugins/releases).

Simply grab the 2.3.1 package, and don't include in-app-billing-service-aidl.jar if you are getting this file from some other billing plugin.
