### ISSUE TITLE
Ads not showing

### ISSUE THREAD

**Issue by slayer02** [googleads/googleads-mobile-plugins#60]
I implemented the plugin correctly and did everything as needed, however ads still dont show on my android devices.Oh and when i try to click request interstitial the application just crashes. (The requests are being called). Please help somebody!

**Comment by ericleich** [comment]
Do you have logcat output for why the request is failing? An error code or stack trace?

My initial guess is you forgot to put the google-play-services_lib/ folder in Assets/Plugins/Android, so when you try to request an ad, the app crashes because it can't find the ads classes it needs to make ad requests.

**Comment by rampara** [comment]
Closing due to non-response. If this is still an issue feel free to reach out at the support group.

- Ram
