### ISSUE TITLE
Add Network Extra

### ISSUE THREAD

**Issue by paradizIscool** [googleads/googleads-mobile-plugins#80]
Hi,

I'm trying to add networkExtra to mediate flurry, but I can't find a way to do this, can somebody help me ?

**Comment by ericleich** [comment]
Hi there,

Setting network extras on mediation networks is not directly supported from the API of the plugin. This isn't really something the plugin can feasibly implement either, since the network extras classes are developed by the third party networks and it doesn't scale to wrap an API around each one of the third party network extras.

You can achieve this behavior yourself by modifying the plugin code to add in support for Flurry extras. You can see how the AdMob extras were added [here](https://github.com/googleads/googleads-mobile-plugins/blob/master/unity/source/Assets/GoogleMobileAds/Platforms/Android/Utils.cs#L125-L126). For Flurry, you could update this code to also create an AndroidJavaObject for the Flurry extras class and add it to the network extras.

**Comment by paradizIscool** [comment]
Thank's
