### ISSUE TITLE
Calling "Destroy()" on not loaded BannerView doesn't destroy it

### ISSUE THREAD

**Issue by grng** [googleads/googleads-mobile-plugins#83]
I show a banner when main menu appears and destroy it when user goes to another menu.

But if banner had no time to load (user changed menu in a second) then it appears in another menu despite being destroyed previously.

**Comment by wingsoftheblackbird** [comment]
Even though you did say Destroy() doesnt destroy it still i would like to clarify, Are you calling the bannerView.Destroy() by code? Or are you expecting it to go out of scope and destroy itself?
because i did it by code and it seems to be woring...

**Comment by rampara** [comment]
This issue has been fixed in the latest release of the Google Mobile Ads Unity Plugin. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram
