### ISSUE TITLE
bannerView late loading

### ISSUE THREAD

**Issue by wingsoftheblackbird** [googleads/googleads-mobile-plugins#84]
Loading the bannerView in one scene and changing the scene quickly before the bannerView can be loaded results in loading of the bannerView in another scene and the bannerView becomes unreferenced so cant be destroyed(Unless through a previously assigned global reference)!

**Comment by rampara** [comment]
This issue has been fixed in the latest release of the Google Mobile Ads Unity Plugin. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram
