### ISSUE TITLE
Add Left and Right options for ad position?

### ISSUE THREAD

**Issue by Brainversation** [googleads/googleads-mobile-plugins#85]
I am using the unity plugin and the orientation of my game is landscape. I would like the ad to show as if it was portrait-top. 
In the banner class can you make it so there are options for right and left, or something to help remedy the situation.

Thank you in advance!

**Comment by rampara** [comment]
The current version of the plugin is now v2.2 and includes support for additional banner positions. If you are running Unity 5.0 you will have to delete the top-level Android manifest from the Assets/Plugins/Android folder. If you are running on older versions of Unity, replace the top-level manifest file with the one linked below.

https://drive.google.com/a/google.com/file/d/0B3mVbrRS6xpKWDQ5SGVlVUx3clU/view?usp=sharing

Ram

**Comment by Brainversation** [comment]
I appreciate the update but that does not solve my problem. I researched online and it seems like the only way to do what I want is a mixture of gravity and animation for rotation.

Thanks for trying.

**Comment by ericleich** [comment]
While I can't find explicit text that says this, I think rotating the ad 90 degrees so it effectively takes up 50x320 in landscape is actually against AdMob policy. At the minimum, it isn't a good user experience since the user can't view the ad without rotating their device or turning their head awkwardly. So this isn't something the plugin will officially support.

If banners without rotation don't make sense for your game, I'd recommend thinking about full screen interstitials in between levels instead.

**Comment by Brainversation** [comment]
The game is meant to be played portrait but I built it in landscape to make it easier to program. I think I will go for full screen ads.

I'd love an update if you ever find a way to do this.

Thanks again for your time and help!
